import collections as c
de = c.deque('India')
print("deque", de)
print("length",len(de))
print("Left end", de[0])
print("Right end",de[-1])
#de.remove('n')
#print(de)

#extend()
de.extend("Is a great company")
print("After entend",de)
de.append("No body can divide")
print("after appending",de)
de.extendleft("Before BC")
print("left extend",de)

#pop()
de.pop()
print("after pop, the queue",de)
de.popleft()
print("after popleft",de)

print("\n#### Elements rotation\################\n")
de1 = c.deque(range(6))
print(de1)
de1.rotate(2)
print("Right rotation",de1)
de1.rotate(-2)
print("Left rotation",de1)